"""add roles table

Revision ID: 375a7c3ba3b0
Revises: 358de51fc981
Create Date: 2026-05-18 20:57:41.878987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375a7c3ba3b0'
down_revision: Union[str, Sequence[str], None] = '358de51fc981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_members', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_members', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_members', 'role')
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    op.add_column('project_members', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
