"""add unique constraint to role name

Revision ID: 14a7244eef7f
Revises: 8d7015eb2291
Create Date: 2026-06-12 04:35:22.667039

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "14a7244eef7f"
down_revision: Union[str, Sequence[str], None] = "8d7015eb2291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "role", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role", type_="unique")
    # ### end Alembic commands ###
